version: '3'
services:
  db:
    build:
      context: .
      dockerfile: Dockerfile-db
    volumes:
      - scuruto-db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: scuruto
      POSTGRES_PASSWORD: scuruto
      POSTGRES_DB: scuruto
      POSTGRES_INITDB_ARGS: "-E UTF8 -T template0 --lc-collate=ja_JP.UTF-8 --lc-ctype=ja_JP.UTF-8"
  app:
    build:
      context: .
      dockerfile: Dockerfile-app
    ports:
      - 8080:8080
    links:
      - db
    volumes:
      - scuruto-app-upload:/var/scuruto/upload
    environment:
      DATABASE_HOST: db:5432
      DATABASE_DBNAME: scuruto
      DATABASE_USER: scuruto
      DATABASE_PASSWORD: scuruto
      SITE_NAME: Scuruto:local
      SITE_TITLE: Scuruto
      LOGIN_PROVIDOR: app
      UPLOAD_DESTINATION: local
      LOCAL_UPLOAD_BASE_DIR: /var/scuruto/upload
      LOCAL_UPLOAD_BASE_URL: /static/uploads
volumes:
  scuruto-db-data:
  scuruto-app-upload:
